version: '2'

services:
  netutils:
    image: flungo/netutils
    container_name: netutils

  credover:
    build: ./Cr3d0v3r
    container_name: credover

  datasploit:
    build: ./datasploit
    container_name: datasploit

  dcrawl:
    build: ./dcrawl
    container_name: dcrawl

  gitminer:
    build: ./gitminer
    container_name: gitminer

  golismero:
    build: ./golismero
    container_name: golismero

  nmap:
    build: ./nmap
    container_name: nmap

  sqliv:
    build: ./sqliv
    container_name: sqliv


  sqlmap:
    build: ./sqlmap
    container_name: sqlmap

  striker:
    build: ./striker
    container_name: striker

  tulpar:
    build: ./tulpar
    container_name: tulpar

  dcrawl:
    build: ./dcrawl
    container_name: dcrawl

  v3n0m:
    build: ./v3n0m
    container_name: v3n0m

  ufonet:
    build: ./ufonet
    container_name: ufo


  emailharvester:
    build: ./emailHarvester
    container_name: emailHarvester
  brutex:
    build: ./BruteX
    container_name: brutex
  blackwidow:
    build: ./blackwidow
    container_name: blackwidow

  tor:
    image: osminogin/tor-simple
    container_name: tor
    links:
     - credover
     - datasploit
     - dcrawl
     - gitminer
     - golismero
     - nmap
     - sqliv
     - sqlmap
     - striker
     - tulpar
     - v3n0m
     - ufonet
     - brutex
     - blackwidow
     - netutils

  environment:
  - http_proxy="http://127.0.0.1:8118"
  - https_proxy="http://127.0.0.1:8118"
  - ftp_proxy="http://127.0.0.1:8118"
  - HTTP_PROXY="http://127.0.0.1:8118"
  - HTTPS_PROXY="http://127.0.0.1:8118"
  - FTP_PROXY="http://127.0.0.1:8118"
